version: '3.8'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
      - ./api/.env:/var/www/.env
    environment:
      - APP_ENV=local
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "8000:80"
    volumes:
      - ./api/:/var/www
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  node:
    platform: linux/arm64/v8 
    build:
      context: ./web
      dockerfile: Dockerfile
    image: my-laravel-node
    container_name: my-laravel-node
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./web/:/var/www
      - /web/var/www/node_modules
    networks:
      - app-network

  db:
    platform: linux/x86_64 
    image: postgres:15.2-alpine
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local